-- The old fold, discarded rather than migrated.
--
-- **Its rows cannot be carried forward.** `SummingMergeTree` merged every delta
-- for a position into one row, so there is no instant to assign them — 7,274
-- rows standing for 33,139 events, and the events are gone. `ALTER TABLE ADD
-- COLUMN` would give every one of them the epoch, which reads as "before any
-- cut" and is wrong for exactly the queries this exists to serve.
--
-- Nothing is lost: `spoke_events` keeps all 37,407 logs, and `078`-`085` rebuild
-- the fold from them.
DROP TABLE IF EXISTS user_positions;
