-- The reserve registry gains the instant each listing happened at.
--
-- **Small, and not therefore unimportant.** Fourteen rows, and they decide
-- whether a position resolves to an asset at all: a reserve listed after the
-- instant being valued would otherwise hand the page a Hub asset that did not
-- exist yet, and every amount derived from it.
--
-- An `ALTER` rather than a rebuild, as for the collateral flag: this table is
-- already one row per `AddReserve` log and still knows which one. Filled by
-- `095`, because a new column defaults to the epoch and the epoch reads as
-- "before every cut".
ALTER TABLE spoke_reserves ADD COLUMN IF NOT EXISTS block_timestamp DateTime('UTC');
