-- The checkpoint table gains the block's own instant.
--
-- **Distinct from `index_timestamp`, which it duplicates on exactly one kind of
-- row.** `index_timestamp` is the *checkpoint's* time and is NULL on `AddAsset`
-- and `UpdateAssetConfig`, because those rows carry no checkpoint — that is what
-- makes `argMaxIf` pick the right one. `block_timestamp` is on every row, which
-- is what lets the whole relation be cut at an instant instead of column by
-- column. Cutting on `index_timestamp` would drop every listing and config row
-- and blank `underlying`, `decimals` and `liquidity_fee` for the page.
--
-- Filled by `138`-`140`; a new column defaults to the epoch, which reads as
-- before every cut.
ALTER TABLE hub_asset_state ADD COLUMN IF NOT EXISTS block_timestamp DateTime('UTC');
